use anyhow::Result;
use std::fs;
use std::path::Path;

use super::Resources;

pub fn generate(resources: &Resources, output_dir: &Path) -> Result<()> {
    let mut script = String::from("#!/bin/bash\n");
    script.push_str("# Terraform import script — generated by dora2tf\n");
    script.push_str("# Run AFTER terraform init\n\n");

    generate_security_groups(&mut script, resources);
    generate_vpc_subnets(&mut script, resources);
    generate_iam(&mut script, resources);
    generate_ec2_instances(&mut script, resources);

    let path = output_dir.join("import.sh");
    fs::write(&path, &script)?;
    tracing::info!("  Wrote import.sh ({} bytes)", script.len());

    // Make executable on Unix
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&path)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&path, perms)?;
    }

    Ok(())
}

fn generate_security_groups(script: &mut String , resources: &Resources) {

    for sg in &resources.security_groups {
        let name = super::tf_name(&sg.name);
        script.push_str(&format!(
            "terraform import aws_security_group.{} {}\n",
            name, sg.id
        ));
        // Import rules
        for (i, _) in sg.ingress.iter().enumerate() {
            script.push_str(&format!(
                "terraform import aws_security_group_rule.{}_ingress_{} {}_ingress_{}\n",
                name, i, sg.id, i
            ));
        }
    }
    script.push('\n');
}

fn generate_vpc_subnets(script: &mut String, resources: &Resources) {

    for vpc in &resources.vpcs {
        let vname = super::tf_name(&vpc.name);
        script.push_str(&format!("terraform import aws_vpc.{} {}\n", vname, vpc.id));
        for subnet in &vpc.subnets {
            let sname = super::tf_name(&subnet.name);
            script.push_str(&format!(
                "terraform import aws_subnet.{} {}\n",
                sname, subnet.id
            ));
        }
    }
    script.push('\n');
}

fn generate_iam(script: &mut String, resources: &Resources) {

    for role in &resources.roles {
        let rname = super::tf_name(&role.name);
        script.push_str(&format!(
            "terraform import aws_iam_role.{} {}\n",
            rname, role.name
        ));
    }
    script.push('\n');
}

fn generate_ec2_instances(script: &mut String, resources: &Resources) {

    for inst in &resources.instances {
        let name = super::tf_name(&inst.name);
        script.push_str(&format!("terraform import aws_instance.{} {}\n", name, inst.id));
    }

}

