use anyhow::Result;
use std::fs;
use std::path::Path;

use super::Resources;

pub fn generate(resources: &Resources, output_dir: &Path) -> Result<()> {
    let mut script = String::from("#!/bin/bash\n");
    script.push_str("# Terraform import script — generated by dora2tf\n");
    script.push_str("# Run AFTER terraform init\n\n");

    // 1. Security Groups first (dependencies for instances)
    for sg in &resources.security_groups {
        let name = super::tf_unique_name(&sg.name, &sg.id);
        script.push_str(&format!(
            "terraform import aws_security_group.{} {}\n",
            name, sg.id
        ));
        // Import rules
        for rule in &sg.ingress {
            let rname = super::tf_rule_name(&name, "ingress", &rule.protocol, rule.from_port);
            script.push_str(&format!(
                "terraform import aws_security_group_rule.{} {}_ingress_{}_{}\n",
                rname, sg.id, rule.protocol, rule.from_port
            ));
        }
    }
    script.push('\n');

    // 2. VPCs + subnets
    for vpc in &resources.vpcs {
        let vname = super::tf_unique_name(&vpc.name, &vpc.id);
        script.push_str(&format!("terraform import aws_vpc.{} {}\n", vname, vpc.id));
        for subnet in &vpc.subnets {
            let sname = super::tf_unique_name(&subnet.name, &subnet.id);
            script.push_str(&format!(
                "terraform import aws_subnet.{} {}\n",
                sname, subnet.id
            ));
        }
    }
    script.push('\n');

    // 3. IAM roles
    for role in &resources.roles {
        let rname = super::tf_unique_name(&role.name, &role.name);
        script.push_str(&format!(
            "terraform import aws_iam_role.{} {}\n",
            rname, role.name
        ));
    }
    script.push('\n');

    // 4. EC2 instances (last — depend on SG + subnet)
    for inst in &resources.instances {
        let name = super::tf_unique_name(&inst.name, &inst.id);
        script.push_str(&format!(
            "terraform import aws_instance.{} {}\n",
            name, inst.id
        ));
    }

    let path = output_dir.join("import.sh");
    fs::write(&path, &script)?;
    tracing::info!("  Wrote import.sh ({} bytes)", script.len());

    // Make executable on Unix
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&path)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&path, perms)?;
    }

    Ok(())
}
