mod ec2;
mod iam;
pub mod imports;
mod sg;
mod vpc;

use std::collections::{HashMap, HashSet};
use std::fmt::Write as FmtWrite;
use std::fs;
use std::io::Write;
use std::path::Path;
use anyhow::Result;

/// Shared resource collection passed from scanner to generator.
#[derive(Default)]
pub struct Resources {
    pub instances:       Vec<crate::scanner::ec2::Ec2Instance>,
    pub security_groups: Vec<crate::scanner::sg::SecurityGroup>,
    pub vpcs:            Vec<crate::scanner::vpc::VpcInfo>,
    pub roles:           Vec<crate::scanner::iam::IamRole>,
}

/// Generate: shared.tf + per-instance files. No duplicates.
pub fn generate_all(resources: &Resources, output_dir: &Path, import_script: bool) -> Result<()> {
    std::fs::create_dir_all(output_dir)?;

    // ── Count usage ────────────────────────────────────────────────────
    let mut sg_usage: HashMap<String, usize> = HashMap::new();
    let mut subnet_usage: HashMap<String, usize> = HashMap::new();
    let mut vpc_usage: HashMap<String, usize> = HashMap::new();

    for inst in &resources.instances {
        for sg_id in &inst.security_groups {
            *sg_usage.entry(sg_id.clone()).or_insert(0) += 1;
        }
        if !inst.subnet_id.is_empty() {
            *subnet_usage.entry(inst.subnet_id.clone()).or_insert(0) += 1;
            // Find which VPC this subnet belongs to
            for vpc in &resources.vpcs {
                if vpc.subnets.iter().any(|s| s.id == inst.subnet_id) {
                    *vpc_usage.entry(vpc.id.clone()).or_insert(0) += 1;
                }
            }
        }
    }

    // Separate: shared (used by 2+) vs exclusive (used by 1)
    let shared_sg_ids: HashSet<String> = sg_usage.iter()
        .filter(|(_, &c)| c > 1).map(|(id, _)| id.clone()).collect();
    let shared_subnet_ids: HashSet<String> = subnet_usage.iter()
        .filter(|(_, &c)| c > 1).map(|(id, _)| id.clone()).collect();
    let shared_vpc_ids: HashSet<String> = vpc_usage.iter()
        .filter(|(_, &c)| c > 1).map(|(id, _)| id.clone()).collect();

    // ── shared.tf ─────────────────────────────────────────────────────
    let mut shared_tf = String::new();
    writeln!(&mut shared_tf, "# Shared resources — used by multiple instances")?;
    writeln!(&mut shared_tf, "# Generated by dora2tf\n")?;

    // Shared SGs (used by 2+ instances)
    for sg in &resources.security_groups {
        if shared_sg_ids.contains(&sg.id) {
            sg::generate_one(sg, &mut shared_tf)?;
        }
    }
    // Shared VPCs + subnets
    for vpc in &resources.vpcs {
        if shared_vpc_ids.contains(&vpc.id) {
            vpc::generate_vpc_only(vpc, &mut shared_tf)?;
            for sub in &vpc.subnets {
                if shared_subnet_ids.contains(&sub.id) {
                    vpc::generate_subnet_only(vpc, sub, &mut shared_tf)?;
                }
            }
        }
    }
    // IAM roles always shared
    iam::generate(&resources.roles, &mut shared_tf)?;

    write_if("shared.tf", output_dir, &shared_tf)?;

    // ── Imports ────────────────────────────────────────────────────────
    if import_script {
        imports::generate_shared(
            resources, &shared_sg_ids, &shared_subnet_ids, &shared_vpc_ids, output_dir,
        )?;
    }

    // ── Per-instance files ────────────────────────────────────────────
    let instances_dir = output_dir.join("instances");
    std::fs::create_dir_all(&instances_dir)?;

    for inst in &resources.instances {
        let name = tf_name(&inst.name);
        let filename = format!("{}.tf", name);
        let mut content = String::new();
        ec2::generate_one(
            inst,
            &resources.security_groups,
            &resources.vpcs,
            &shared_sg_ids,
            &shared_subnet_ids,
            &shared_vpc_ids,
            &mut content,
        )?;
        write_if(&filename, &instances_dir, &content)?;

        if import_script {
            imports::generate_per_instance(
                inst, &resources.security_groups, &resources.vpcs,
                &shared_sg_ids, &shared_subnet_ids, &shared_vpc_ids,
                &instances_dir,
            )?;
        }
    }

    Ok(())
}

/// Dry run.
pub fn generate_dry(resources: &Resources) -> Result<()> {
    println!("Would generate:");
    println!("  shared.tf              — shared SGs, VPCs, IAM");
    println!("  instances/             — {} per-instance files", resources.instances.len());
    Ok(())
}

fn write_if(filename: &str, dir: &Path, content: &str) -> Result<()> {
    if content.trim().is_empty() {
        return Ok(());
    }
    let path = dir.join(filename);
    let mut f = fs::File::create(&path)?;
    f.write_all(content.as_bytes())?;
    tracing::info!("  Wrote {} ({} bytes)", path.display(), content.len());
    Ok(())
}

/// Normalize a tag Name to a Terraform-safe identifier.
pub fn tf_name(raw: &str) -> String {
    let s = raw.to_lowercase().replace(['-', ' ', '.', '/'], "_");
    let s: String = s.chars().filter(|c| c.is_alphanumeric() || *c == '_').collect();
    if s.is_empty() { "unnamed".into() } else { s }
}

/// Quote a tag key if it contains characters invalid in HCL identifiers.
pub fn quote_tag_key(key: &str) -> String {
    let needs_quoting = key.is_empty()
        || key.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false)
        || key.contains(':') || key.contains('-')
        || key.contains('.') || key.contains('/')
        || key.contains(' ') || key.contains('@');
    if needs_quoting { format!("\"{}\"", key) } else { key.to_string() }
}
